# Generated by Django 2.1.2 on 2019-04-26 11:03

from django.db import migrations, models
import django.utils.timezone
import ikofe_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('ikofe_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.ImageField(storage=ikofe_site.models.UUIDFileStorage(), upload_to='pictures/events')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.ImageField(storage=ikofe_site.models.UUIDFileStorage(), upload_to='pictures/events')),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
