# Generated by Django 2.1.2 on 2019-04-26 11:26

from django.db import migrations, models
import ikofe_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('ikofe_site', '0003_auto_20190426_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(storage=ikofe_site.models.UUIDFileStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(storage=ikofe_site.models.UUIDFileStorage(), upload_to=''),
        ),
    ]
