# Generated by Django 2.1.2 on 2019-04-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikofe_site', '0004_auto_20190426_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('video_ad', 'Видеореклама'), ('elevator', 'Реклама в лифтах')], default='video_ad', max_length=50),
        ),
    ]
