# Generated by Django 2.1.2 on 2019-04-27 13:11

from django.db import migrations, models
import ikofe_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('ikofe_site', '0005_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_link',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, storage=ikofe_site.models.UUIDFileStorage(), upload_to=''),
        ),
    ]
