# Generated by Django 2.1.2 on 2019-05-06 11:12

from django.db import migrations, models
import ikofe_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('ikofe_site', '0006_auto_20190427_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='', storage=ikofe_site.models.UUIDFileStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
