# Generated by Django 2.1.2 on 2019-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikofe_site', '0007_auto_20190506_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='pageHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
