# Generated by Django 2.1.2 on 2019-05-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikofe_site', '0008_pagehit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagehit',
            old_name='url',
            new_name='title',
        ),
    ]
